// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/order/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderHandler is an autogenerated mock type for the OrderHandler type
type MockOrderHandler struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, input
func (_m *MockOrderHandler) CreateOrder(ctx context.Context, input *dto.CreateOrderInputDto) (*dto.CreatedOrderOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *dto.CreatedOrderOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderInputDto) (*dto.CreatedOrderOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateOrderInputDto) *dto.CreatedOrderOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreatedOrderOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateOrderInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderById provides a mock function with given fields: ctx, input
func (_m *MockOrderHandler) GetOrderById(ctx context.Context, input *dto.GetOrderByIdInputDto) (*dto.GetOrderByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderById")
	}

	var r0 *dto.GetOrderByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrderByIdInputDto) (*dto.GetOrderByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrderByIdInputDto) *dto.GetOrderByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetOrderByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrders provides a mock function with given fields: ctx, input
func (_m *MockOrderHandler) GetOrders(ctx context.Context, input *dto.GetOrdersInputDto) (*dto.GetOrdersOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 *dto.GetOrdersOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrdersInputDto) (*dto.GetOrdersOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetOrdersInputDto) *dto.GetOrdersOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrdersOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetOrdersInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersCount provides a mock function with given fields: ctx, input
func (_m *MockOrderHandler) GetOrdersCount(ctx context.Context, input *struct{}) (*dto.GetOrdersCountOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersCount")
	}

	var r0 *dto.GetOrdersCountOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) (*dto.GetOrdersCountOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) *dto.GetOrdersCountOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrdersCountOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *struct{}) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatus provides a mock function with given fields: ctx, input
func (_m *MockOrderHandler) UpdateOrderStatus(ctx context.Context, input *dto.UpdateOrderStatusInputDto) (*dto.UpdateOrderStatusOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 *dto.UpdateOrderStatusOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateOrderStatusInputDto) (*dto.UpdateOrderStatusOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateOrderStatusInputDto) *dto.UpdateOrderStatusOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UpdateOrderStatusOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateOrderStatusInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockOrderHandler creates a new instance of MockOrderHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderHandler {
	mock := &MockOrderHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
