// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *MockOrderRepository) CreateOrder(ctx context.Context, order *database.Order) (uuid.UUID, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.Order) (uuid.UUID, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.Order) uuid.UUID); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *MockOrderRepository) GetOrderByID(ctx context.Context, orderID uuid.UUID) (*database.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *database.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*database.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *database.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID, page, pageSize, status, orderBy
func (_m *MockOrderRepository) GetOrdersByUserID(ctx context.Context, userID uuid.UUID, page int64, pageSize int64, status string, orderBy string) ([]database.Order, int64, error) {
	ret := _m.Called(ctx, userID, page, pageSize, status, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []database.Order
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int64, string, string) ([]database.Order, int64, error)); ok {
		return rf(ctx, userID, page, pageSize, status, orderBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int64, string, string) []database.Order); ok {
		r0 = rf(ctx, userID, page, pageSize, status, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, userID, page, pageSize, status, orderBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int64, int64, string, string) error); ok {
		r2 = rf(ctx, userID, page, pageSize, status, orderBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetOrdersCount provides a mock function with given fields: ctx
func (_m *MockOrderRepository) GetOrdersCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderSession provides a mock function with given fields: ctx, orderID, sessionID, sessionURL, expiresAt
func (_m *MockOrderRepository) UpdateOrderSession(ctx context.Context, orderID uuid.UUID, sessionID string, sessionURL string, expiresAt *time.Time) error {
	ret := _m.Called(ctx, orderID, sessionID, sessionURL, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *time.Time) error); ok {
		r0 = rf(ctx, orderID, sessionID, sessionURL, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrderStatus provides a mock function with given fields: ctx, orderID, status
func (_m *MockOrderRepository) UpdateOrderStatus(ctx context.Context, orderID uuid.UUID, status database.OrderStatus) error {
	ret := _m.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, database.OrderStatus) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
