services:
  backend:
    image: phuriphon47/lorem-e-commerce-backend:latest
    container_name: lorem-backend-prod
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

include:
  - docker-compose.db.yml