// Code generated by mockery v2.53.6. DO NOT EDIT.

package gateway

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPaymentGateway is an autogenerated mock type for the PaymentGateway type
type MockPaymentGateway struct {
	mock.Mock
}

// CreateCheckoutSession provides a mock function with given fields: orderID, totalPrice, successURL, cancelURL
func (_m *MockPaymentGateway) CreateCheckoutSession(orderID uuid.UUID, totalPrice float32, successURL string, cancelURL string) (string, string, int64, error) {
	ret := _m.Called(orderID, totalPrice, successURL, cancelURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 string
	var r1 string
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, float32, string, string) (string, string, int64, error)); ok {
		return rf(orderID, totalPrice, successURL, cancelURL)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, float32, string, string) string); ok {
		r0 = rf(orderID, totalPrice, successURL, cancelURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, float32, string, string) string); ok {
		r1 = rf(orderID, totalPrice, successURL, cancelURL)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, float32, string, string) int64); ok {
		r2 = rf(orderID, totalPrice, successURL, cancelURL)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(uuid.UUID, float32, string, string) error); ok {
		r3 = rf(orderID, totalPrice, successURL, cancelURL)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ExtractOrderEventFromWebhook provides a mock function with given fields: payload, c
func (_m *MockPaymentGateway) ExtractOrderEventFromWebhook(payload []byte, c echo.Context) (string, string, error) {
	ret := _m.Called(payload, c)

	if len(ret) == 0 {
		panic("no return value specified for ExtractOrderEventFromWebhook")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte, echo.Context) (string, string, error)); ok {
		return rf(payload, c)
	}
	if rf, ok := ret.Get(0).(func([]byte, echo.Context) string); ok {
		r0 = rf(payload, c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]byte, echo.Context) string); ok {
		r1 = rf(payload, c)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func([]byte, echo.Context) error); ok {
		r2 = rf(payload, c)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// VerifySessionPayment provides a mock function with given fields: sessionID
func (_m *MockPaymentGateway) VerifySessionPayment(sessionID string) (bool, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for VerifySessionPayment")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPaymentGateway creates a new instance of MockPaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentGateway {
	mock := &MockPaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
