// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/cart/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockCartHandler is an autogenerated mock type for the CartHandler type
type MockCartHandler struct {
	mock.Mock
}

// CreateCartItem provides a mock function with given fields: ctx, input
func (_m *MockCartHandler) CreateCartItem(ctx context.Context, input *dto.CreateCartItemInputDto) (*dto.CreateCartItemOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCartItem")
	}

	var r0 *dto.CreateCartItemOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCartItemInputDto) (*dto.CreateCartItemOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCartItemInputDto) *dto.CreateCartItemOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateCartItemOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateCartItemInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCartItems provides a mock function with given fields: ctx, input
func (_m *MockCartHandler) DeleteCartItems(ctx context.Context, input *dto.DeleteCartItemsInputDto) (*dto.DeleteCartItemsOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCartItems")
	}

	var r0 *dto.DeleteCartItemsOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteCartItemsInputDto) (*dto.DeleteCartItemsOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteCartItemsInputDto) *dto.DeleteCartItemsOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteCartItemsOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DeleteCartItemsInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditCartItem provides a mock function with given fields: ctx, input
func (_m *MockCartHandler) EditCartItem(ctx context.Context, input *dto.EditCartItemInputDto) (*dto.EditCartItemOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for EditCartItem")
	}

	var r0 *dto.EditCartItemOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.EditCartItemInputDto) (*dto.EditCartItemOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.EditCartItemInputDto) *dto.EditCartItemOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.EditCartItemOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.EditCartItemInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCartByUserId provides a mock function with given fields: ctx, input
func (_m *MockCartHandler) GetCartByUserId(ctx context.Context, input *dto.GetCartByUserIdInputDto) (*dto.GetCartByUserIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByUserId")
	}

	var r0 *dto.GetCartByUserIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCartByUserIdInputDto) (*dto.GetCartByUserIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCartByUserIdInputDto) *dto.GetCartByUserIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetCartByUserIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetCartByUserIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCartHandler creates a new instance of MockCartHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartHandler {
	mock := &MockCartHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
