// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetUserByID(ctx context.Context, userID uuid.UUID) (*database.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*database.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *database.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, page, pageSize, search, order
func (_m *MockUserRepository) GetUsers(ctx context.Context, page int64, pageSize int64, search string, order string) ([]database.User, int64, error) {
	ret := _m.Called(ctx, page, pageSize, search, order)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []database.User
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) ([]database.User, int64, error)); ok {
		return rf(ctx, page, pageSize, search, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) []database.User); ok {
		r0 = rf(ctx, page, pageSize, search, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, page, pageSize, search, order)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, string, string) error); ok {
		r2 = rf(ctx, page, pageSize, search, order)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUsersCount provides a mock function with given fields: ctx
func (_m *MockUserRepository) GetUsersCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) UpdateUser(ctx context.Context, user *database.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
