// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

// SendResetPasswordEmail provides a mock function with given fields: toEmail, userName, resetLink
func (_m *MockEmailService) SendResetPasswordEmail(toEmail string, userName string, resetLink string) error {
	ret := _m.Called(toEmail, userName, resetLink)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(toEmail, userName, resetLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
