// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/user/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockUserHandler is an autogenerated mock type for the UserHandler type
type MockUserHandler struct {
	mock.Mock
}

// GetMe provides a mock function with given fields: ctx, input
func (_m *MockUserHandler) GetMe(ctx context.Context, input *dto.GetMeInputDto) (*dto.GetMeOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *dto.GetMeOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetMeInputDto) (*dto.GetMeOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetMeInputDto) *dto.GetMeOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetMeOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetMeInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: ctx, input
func (_m *MockUserHandler) GetUserById(ctx context.Context, input *dto.GetUserByIdInputDto) (*dto.GetUserByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *dto.GetUserByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetUserByIdInputDto) (*dto.GetUserByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetUserByIdInputDto) *dto.GetUserByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetUserByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetUserByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, input
func (_m *MockUserHandler) GetUsers(ctx context.Context, input *dto.GetUsersInputDto) (*dto.GetUsersOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *dto.GetUsersOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetUsersInputDto) (*dto.GetUsersOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetUsersInputDto) *dto.GetUsersOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetUsersOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetUsersInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersCount provides a mock function with given fields: ctx, input
func (_m *MockUserHandler) GetUsersCount(ctx context.Context, input *struct{}) (*dto.GetUsersCountOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersCount")
	}

	var r0 *dto.GetUsersCountOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) (*dto.GetUsersCountOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) *dto.GetUsersCountOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetUsersCountOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *struct{}) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMe provides a mock function with given fields: ctx, input
func (_m *MockUserHandler) UpdateMe(ctx context.Context, input *dto.UpdateMeInputDto) (*dto.UpdateMeOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMe")
	}

	var r0 *dto.UpdateMeOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateMeInputDto) (*dto.UpdateMeOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateMeInputDto) *dto.UpdateMeOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UpdateMeOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateMeInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockUserHandler creates a new instance of MockUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserHandler {
	mock := &MockUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
