// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/auth/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthHandler is an autogenerated mock type for the AuthHandler type
type MockAuthHandler struct {
	mock.Mock
}

// ForgotPassword provides a mock function with given fields: ctx, input
func (_m *MockAuthHandler) ForgotPassword(ctx context.Context, input *dto.ForgotPasswordInputDto) (*dto.ForgotPasswordOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 *dto.ForgotPasswordOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ForgotPasswordInputDto) (*dto.ForgotPasswordOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ForgotPasswordInputDto) *dto.ForgotPasswordOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ForgotPasswordOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ForgotPasswordInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: ctx, input
func (_m *MockAuthHandler) RegisterUser(ctx context.Context, input *dto.RegisterUserInputDto) (*dto.RegisterUserOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *dto.RegisterUserOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterUserInputDto) (*dto.RegisterUserOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RegisterUserInputDto) *dto.RegisterUserOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RegisterUserOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RegisterUserInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, input
func (_m *MockAuthHandler) ResetPassword(ctx context.Context, input *dto.ResetPasswordInputDto) (*dto.ResetPasswordOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *dto.ResetPasswordOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ResetPasswordInputDto) (*dto.ResetPasswordOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ResetPasswordInputDto) *dto.ResetPasswordOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResetPasswordOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ResetPasswordInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignInUser provides a mock function with given fields: ctx, input
func (_m *MockAuthHandler) SignInUser(ctx context.Context, input *dto.SignInUserInputDto) (*dto.SignInUserOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SignInUser")
	}

	var r0 *dto.SignInUserOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SignInUserInputDto) (*dto.SignInUserOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SignInUserInputDto) *dto.SignInUserOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SignInUserOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SignInUserInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignOutUser provides a mock function with given fields: ctx, input
func (_m *MockAuthHandler) SignOutUser(ctx context.Context, input *dto.SignOutUserInputDto) (*dto.SignOutUserOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SignOutUser")
	}

	var r0 *dto.SignOutUserOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SignOutUserInputDto) (*dto.SignOutUserOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.SignOutUserInputDto) *dto.SignOutUserOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SignOutUserOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.SignOutUserInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAuthHandler creates a new instance of MockAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthHandler {
	mock := &MockAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
