// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWebsocketService is an autogenerated mock type for the WebsocketService type
type MockWebsocketService struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *MockWebsocketService) Run(ctx context.Context) {
	_m.Called(ctx)
}

// SendToUser provides a mock function with given fields: userID, message
func (_m *MockWebsocketService) SendToUser(userID uuid.UUID, message WSPayload) {
	_m.Called(userID, message)
}

// WebsocketHandler provides a mock function with given fields: c
func (_m *MockWebsocketService) WebsocketHandler(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for WebsocketHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWebsocketService creates a new instance of MockWebsocketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsocketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsocketService {
	mock := &MockWebsocketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
