// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/product/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockProductHandler is an autogenerated mock type for the ProductHandler type
type MockProductHandler struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, input
func (_m *MockProductHandler) CreateProduct(ctx context.Context, input *dto.CreateProductInputDto) (*dto.CreatedProductOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *dto.CreatedProductOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateProductInputDto) (*dto.CreatedProductOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateProductInputDto) *dto.CreatedProductOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreatedProductOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateProductInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProductById provides a mock function with given fields: ctx, input
func (_m *MockProductHandler) DeleteProductById(ctx context.Context, input *dto.DeleteProductByIdInputDto) (*dto.DeleteProductByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductById")
	}

	var r0 *dto.DeleteProductByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteProductByIdInputDto) (*dto.DeleteProductByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteProductByIdInputDto) *dto.DeleteProductByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteProductByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DeleteProductByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductById provides a mock function with given fields: ctx, input
func (_m *MockProductHandler) GetProductById(ctx context.Context, input *dto.GetProductByIdInputDto) (*dto.GetProductByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetProductById")
	}

	var r0 *dto.GetProductByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetProductByIdInputDto) (*dto.GetProductByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetProductByIdInputDto) *dto.GetProductByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetProductByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetProductByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: ctx, input
func (_m *MockProductHandler) GetProducts(ctx context.Context, input *dto.GetProductsInputDto) (*dto.GetProductsOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 *dto.GetProductsOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetProductsInputDto) (*dto.GetProductsOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetProductsInputDto) *dto.GetProductsOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetProductsOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetProductsInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductsCount provides a mock function with given fields: ctx, input
func (_m *MockProductHandler) GetProductsCount(ctx context.Context, input *struct{}) (*dto.GetProductsCountOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsCount")
	}

	var r0 *dto.GetProductsCountOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) (*dto.GetProductsCountOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) *dto.GetProductsCountOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetProductsCountOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *struct{}) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, input
func (_m *MockProductHandler) UpdateProduct(ctx context.Context, input *dto.UpdateProductInputDto) (*dto.UpdatedProductOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *dto.UpdatedProductOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateProductInputDto) (*dto.UpdatedProductOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateProductInputDto) *dto.UpdatedProductOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UpdatedProductOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateProductInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockProductHandler creates a new instance of MockProductHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductHandler {
	mock := &MockProductHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
