// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, category
func (_m *MockCategoryRepository) CreateCategory(ctx context.Context, category *database.Category) (uuid.UUID, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.Category) (uuid.UUID, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.Category) uuid.UUID); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.Category) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategoryByID provides a mock function with given fields: ctx, catID
func (_m *MockCategoryRepository) DeleteCategoryByID(ctx context.Context, catID uuid.UUID) error {
	ret := _m.Called(ctx, catID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategoryByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, catID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCategories provides a mock function with given fields: ctx
func (_m *MockCategoryRepository) GetCategories(ctx context.Context) ([]database.Category, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []database.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Category, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoriesCount provides a mock function with given fields: ctx
func (_m *MockCategoryRepository) GetCategoriesCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoriesCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ctx, catID
func (_m *MockCategoryRepository) GetCategoryByID(ctx context.Context, catID uuid.UUID) (*database.Category, error) {
	ret := _m.Called(ctx, catID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *database.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*database.Category, error)); ok {
		return rf(ctx, catID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *database.Category); ok {
		r0 = rf(ctx, catID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, catID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategoryByID provides a mock function with given fields: ctx, catID, name
func (_m *MockCategoryRepository) UpdateCategoryByID(ctx context.Context, catID uuid.UUID, name string) error {
	ret := _m.Called(ctx, catID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategoryByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, catID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
