// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockAuthRepository) GetUserByEmail(ctx context.Context, email string) (*struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	IsAdmin      bool
}, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *struct {
		ID           uuid.UUID
		Username     string
		PasswordHash string
		IsAdmin      bool
	}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*struct {
		ID           uuid.UUID
		Username     string
		PasswordHash string
		IsAdmin      bool
	}, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *struct {
		ID           uuid.UUID
		Username     string
		PasswordHash string
		IsAdmin      bool
	}); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*struct {
				ID           uuid.UUID
				Username     string
				PasswordHash string
				IsAdmin      bool
			})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockAuthRepository) GetUserByUsername(ctx context.Context, username string) (*struct {
	ID       uuid.UUID
	Username string
}, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *struct {
		ID       uuid.UUID
		Username string
	}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*struct {
		ID       uuid.UUID
		Username string
	}, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *struct {
		ID       uuid.UUID
		Username string
	}); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*struct {
				ID       uuid.UUID
				Username string
			})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: ctx, user
func (_m *MockAuthRepository) RegisterUser(ctx context.Context, user *database.User) (uuid.UUID, string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 uuid.UUID
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.User) (uuid.UUID, string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.User) uuid.UUID); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.User) string); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *database.User) error); ok {
		r2 = rf(ctx, user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdatePassword provides a mock function with given fields: ctx, userID, newPasswordHash
func (_m *MockAuthRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, newPasswordHash string) error {
	ret := _m.Called(ctx, userID, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
