// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/payment/dto"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentHandler is an autogenerated mock type for the PaymentHandler type
type MockPaymentHandler struct {
	mock.Mock
}

// CreateCheckoutSession provides a mock function with given fields: ctx, input
func (_m *MockPaymentHandler) CreateCheckoutSession(ctx context.Context, input *dto.CreateCheckoutInputDto) (*dto.CreateCheckoutOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 *dto.CreateCheckoutOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCheckoutInputDto) (*dto.CreateCheckoutOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCheckoutInputDto) *dto.CreateCheckoutOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateCheckoutOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateCheckoutInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPaymentsByUserID provides a mock function with given fields: ctx, input
func (_m *MockPaymentHandler) GetUserPaymentsByUserID(ctx context.Context, input *dto.GetPaymentsByUserIdInputDto) (*dto.GetPaymentsByUserIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPaymentsByUserID")
	}

	var r0 *dto.GetPaymentsByUserIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetPaymentsByUserIdInputDto) (*dto.GetPaymentsByUserIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetPaymentsByUserIdInputDto) *dto.GetPaymentsByUserIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetPaymentsByUserIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetPaymentsByUserIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleStripeWebhook provides a mock function with given fields: c
func (_m *MockPaymentHandler) HandleStripeWebhook(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for HandleStripeWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifySession provides a mock function with given fields: ctx, input
func (_m *MockPaymentHandler) VerifySession(ctx context.Context, input *dto.VerifySessionInputDto) (*dto.VerifySessionOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for VerifySession")
	}

	var r0 *dto.VerifySessionOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.VerifySessionInputDto) (*dto.VerifySessionOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.VerifySessionInputDto) *dto.VerifySessionOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VerifySessionOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.VerifySessionInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPaymentHandler creates a new instance of MockPaymentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentHandler {
	mock := &MockPaymentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
