// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/file/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockFileHandler is an autogenerated mock type for the FileHandler type
type MockFileHandler struct {
	mock.Mock
}

// DownLoadFile provides a mock function with given fields: ctx, input
func (_m *MockFileHandler) DownLoadFile(ctx context.Context, input *dto.DownloadFileInputDto) (*dto.DownloadFileOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DownLoadFile")
	}

	var r0 *dto.DownloadFileOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DownloadFileInputDto) (*dto.DownloadFileOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DownloadFileInputDto) *dto.DownloadFileOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DownloadFileOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DownloadFileInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DownloadFileByKey provides a mock function with given fields: ctx, input
func (_m *MockFileHandler) DownloadFileByKey(ctx context.Context, input *dto.DownloadFileByKeyInputDto) (*dto.DownloadFileByKeyOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFileByKey")
	}

	var r0 *dto.DownloadFileByKeyOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DownloadFileByKeyInputDto) (*dto.DownloadFileByKeyOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DownloadFileByKeyInputDto) *dto.DownloadFileByKeyOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DownloadFileByKeyOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DownloadFileByKeyInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllFilesMetadata provides a mock function with given fields: ctx, input
func (_m *MockFileHandler) GetAllFilesMetadata(ctx context.Context, input *dto.GetAllFilesMetadataInputDto) (*dto.GetAllFilesMetadataOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFilesMetadata")
	}

	var r0 *dto.GetAllFilesMetadataOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetAllFilesMetadataInputDto) (*dto.GetAllFilesMetadataOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetAllFilesMetadataInputDto) *dto.GetAllFilesMetadataOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetAllFilesMetadataOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetAllFilesMetadataInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFileMetaByID provides a mock function with given fields: ctx, input
func (_m *MockFileHandler) GetFileMetaByID(ctx context.Context, input *dto.GetFileMetaByIDInputDto) (*dto.GetFileMetaByIDOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMetaByID")
	}

	var r0 *dto.GetFileMetaByIDOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetFileMetaByIDInputDto) (*dto.GetFileMetaByIDOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetFileMetaByIDInputDto) *dto.GetFileMetaByIDOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetFileMetaByIDOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetFileMetaByIDInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: ctx, input
func (_m *MockFileHandler) UploadFile(ctx context.Context, input *dto.UploadFileInputDto) (*dto.UploadFileOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 *dto.UploadFileOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UploadFileInputDto) (*dto.UploadFileOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UploadFileInputDto) *dto.UploadFileOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UploadFileOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UploadFileInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadStaticFile provides a mock function with given fields: ctx, input
func (_m *MockFileHandler) UploadStaticFile(ctx context.Context, input *dto.UploadStaticFileInputDto) (*dto.UploadStaticFileOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadStaticFile")
	}

	var r0 *dto.UploadStaticFileOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UploadStaticFileInputDto) (*dto.UploadStaticFileOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UploadStaticFileInputDto) *dto.UploadStaticFileOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UploadStaticFileOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UploadStaticFileInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockFileHandler creates a new instance of MockFileHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileHandler {
	mock := &MockFileHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
