// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) CreatePayment(ctx context.Context, payment *database.Payment) (uuid.UUID, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.Payment) (uuid.UUID, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.Payment) uuid.UUID); ok {
		r0 = rf(ctx, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPaymentByOrderID provides a mock function with given fields: ctx, orderID, userID
func (_m *MockPaymentRepository) GetUserPaymentByOrderID(ctx context.Context, orderID uuid.UUID, userID uuid.UUID) (*database.Payment, error) {
	ret := _m.Called(ctx, orderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPaymentByOrderID")
	}

	var r0 *database.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*database.Payment, error)); ok {
		return rf(ctx, orderID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *database.Payment); ok {
		r0 = rf(ctx, orderID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPaymentsByUserID provides a mock function with given fields: ctx, userID, page, pageSize, orderBy, status
func (_m *MockPaymentRepository) GetUserPaymentsByUserID(ctx context.Context, userID uuid.UUID, page int64, pageSize int64, orderBy string, status string) ([]database.Payment, int64, error) {
	ret := _m.Called(ctx, userID, page, pageSize, orderBy, status)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPaymentsByUserID")
	}

	var r0 []database.Payment
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int64, string, string) ([]database.Payment, int64, error)); ok {
		return rf(ctx, userID, page, pageSize, orderBy, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, int64, string, string) []database.Payment); ok {
		r0 = rf(ctx, userID, page, pageSize, orderBy, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64, int64, string, string) int64); ok {
		r1 = rf(ctx, userID, page, pageSize, orderBy, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int64, int64, string, string) error); ok {
		r2 = rf(ctx, userID, page, pageSize, orderBy, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdatePaymentStatusByOrderID provides a mock function with given fields: ctx, orderID, status
func (_m *MockPaymentRepository) UpdatePaymentStatusByOrderID(ctx context.Context, orderID uuid.UUID, status string) error {
	ret := _m.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatusByOrderID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
