// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

// CreateCartItem provides a mock function with given fields: ctx, cartItem
func (_m *MockCartRepository) CreateCartItem(ctx context.Context, cartItem *database.CartItem) (uuid.UUID, error) {
	ret := _m.Called(ctx, cartItem)

	if len(ret) == 0 {
		panic("no return value specified for CreateCartItem")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.CartItem) (uuid.UUID, error)); ok {
		return rf(ctx, cartItem)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.CartItem) uuid.UUID); ok {
		r0 = rf(ctx, cartItem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.CartItem) error); ok {
		r1 = rf(ctx, cartItem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditCartItem provides a mock function with given fields: ctx, cartId, productId, quantity
func (_m *MockCartRepository) EditCartItem(ctx context.Context, cartId uuid.UUID, productId uuid.UUID, quantity uint) error {
	ret := _m.Called(ctx, cartId, productId, quantity)

	if len(ret) == 0 {
		panic("no return value specified for EditCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uint) error); ok {
		r0 = rf(ctx, cartId, productId, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCartByUserId provides a mock function with given fields: ctx, userId
func (_m *MockCartRepository) GetCartByUserId(ctx context.Context, userId uuid.UUID) (*database.Cart, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByUserId")
	}

	var r0 *database.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*database.Cart, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *database.Cart); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCartItem provides a mock function with given fields: ctx, cartId, productId
func (_m *MockCartRepository) GetCartItem(ctx context.Context, cartId uuid.UUID, productId uuid.UUID) (*database.CartItem, error) {
	ret := _m.Called(ctx, cartId, productId)

	if len(ret) == 0 {
		panic("no return value specified for GetCartItem")
	}

	var r0 *database.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*database.CartItem, error)); ok {
		return rf(ctx, cartId, productId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *database.CartItem); ok {
		r0 = rf(ctx, cartId, productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, cartId, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveCartItems provides a mock function with given fields: ctx, cartId, productIds
func (_m *MockCartRepository) RemoveCartItems(ctx context.Context, cartId uuid.UUID, productIds []uuid.UUID) error {
	ret := _m.Called(ctx, cartId, productIds)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCartItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, cartId, productIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
