// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

// AddProductStocks provides a mock function with given fields: ctx, additions
func (_m *MockProductRepository) AddProductStocks(ctx context.Context, additions []StockDeduction) error {
	ret := _m.Called(ctx, additions)

	if len(ret) == 0 {
		panic("no return value specified for AddProductStocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []StockDeduction) error); ok {
		r0 = rf(ctx, additions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProduct provides a mock function with given fields: ctx, product
func (_m *MockProductRepository) CreateProduct(ctx context.Context, product *database.Product) (uuid.UUID, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.Product) (uuid.UUID, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.Product) uuid.UUID); ok {
		r0 = rf(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeductProductStocks provides a mock function with given fields: ctx, deductions
func (_m *MockProductRepository) DeductProductStocks(ctx context.Context, deductions []StockDeduction) error {
	ret := _m.Called(ctx, deductions)

	if len(ret) == 0 {
		panic("no return value specified for DeductProductStocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []StockDeduction) error); ok {
		r0 = rf(ctx, deductions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProductByID provides a mock function with given fields: ctx, productID
func (_m *MockProductRepository) DeleteProductByID(ctx context.Context, productID uuid.UUID) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProductByID provides a mock function with given fields: ctx, productID
func (_m *MockProductRepository) GetProductByID(ctx context.Context, productID uuid.UUID) (*database.Product, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *database.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*database.Product, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *database.Product); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductStock provides a mock function with given fields: ctx, productId
func (_m *MockProductRepository) GetProductStock(ctx context.Context, productId uuid.UUID) (uint, error) {
	ret := _m.Called(ctx, productId)

	if len(ret) == 0 {
		panic("no return value specified for GetProductStock")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uint, error)); ok {
		return rf(ctx, productId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uint); ok {
		r0 = rf(ctx, productId)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: ctx, page, pageSize, category, search, order
func (_m *MockProductRepository) GetProducts(ctx context.Context, page int64, pageSize int64, category string, search string, order string) ([]database.Product, int64, error) {
	ret := _m.Called(ctx, page, pageSize, category, search, order)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []database.Product
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string) ([]database.Product, int64, error)); ok {
		return rf(ctx, page, pageSize, category, search, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string) []database.Product); ok {
		r0 = rf(ctx, page, pageSize, category, search, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, string) int64); ok {
		r1 = rf(ctx, page, pageSize, category, search, order)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, string, string, string) error); ok {
		r2 = rf(ctx, page, pageSize, category, search, order)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetProductsByIDs provides a mock function with given fields: ctx, productIDs
func (_m *MockProductRepository) GetProductsByIDs(ctx context.Context, productIDs []uuid.UUID) ([]database.Product, error) {
	ret := _m.Called(ctx, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByIDs")
	}

	var r0 []database.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]database.Product, error)); ok {
		return rf(ctx, productIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []database.Product); ok {
		r0 = rf(ctx, productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, productIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductsCount provides a mock function with given fields: ctx
func (_m *MockProductRepository) GetProductsCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProductByID provides a mock function with given fields: ctx, productID, updateData
func (_m *MockProductRepository) UpdateProductByID(ctx context.Context, productID uuid.UUID, updateData map[string]interface{}) error {
	ret := _m.Called(ctx, productID, updateData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProductByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]interface{}) error); ok {
		r0 = rf(ctx, productID, updateData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
