// Code generated by mockery v2.53.6. DO NOT EDIT.

package handler

import (
	context "context"
	dto "lorem-backend/internal/modules/category/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryHandler is an autogenerated mock type for the CategoryHandler type
type MockCategoryHandler struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, input
func (_m *MockCategoryHandler) CreateCategory(ctx context.Context, input *dto.CreateCategoryInputDto) (*dto.CreateCategoryOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *dto.CreateCategoryOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCategoryInputDto) (*dto.CreateCategoryOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCategoryInputDto) *dto.CreateCategoryOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateCategoryOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateCategoryInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategory provides a mock function with given fields: ctx, input
func (_m *MockCategoryHandler) DeleteCategory(ctx context.Context, input *dto.DeleteCategoryByIdInputDto) (*dto.DeleteCategoryByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 *dto.DeleteCategoryByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteCategoryByIdInputDto) (*dto.DeleteCategoryByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteCategoryByIdInputDto) *dto.DeleteCategoryByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteCategoryByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DeleteCategoryByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategories provides a mock function with given fields: ctx, _a1
func (_m *MockCategoryHandler) GetCategories(ctx context.Context, _a1 *struct{}) (*dto.GetCategoriesOutputDto, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 *dto.GetCategoriesOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) (*dto.GetCategoriesOutputDto, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) *dto.GetCategoriesOutputDto); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetCategoriesOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *struct{}) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoriesCount provides a mock function with given fields: ctx, input
func (_m *MockCategoryHandler) GetCategoriesCount(ctx context.Context, input *struct{}) (*dto.GetCategoriesCountOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoriesCount")
	}

	var r0 *dto.GetCategoriesCountOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) (*dto.GetCategoriesCountOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *struct{}) *dto.GetCategoriesCountOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetCategoriesCountOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *struct{}) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryById provides a mock function with given fields: ctx, input
func (_m *MockCategoryHandler) GetCategoryById(ctx context.Context, input *dto.GetCategoryByIdInputDto) (*dto.GetCategoryByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryById")
	}

	var r0 *dto.GetCategoryByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCategoryByIdInputDto) (*dto.GetCategoryByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetCategoryByIdInputDto) *dto.GetCategoryByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetCategoryByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetCategoryByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: ctx, input
func (_m *MockCategoryHandler) UpdateCategory(ctx context.Context, input *dto.UpdateCategoryByIdInputDto) (*dto.UpdateCategoryByIdOutputDto, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 *dto.UpdateCategoryByIdOutputDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateCategoryByIdInputDto) (*dto.UpdateCategoryByIdOutputDto, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateCategoryByIdInputDto) *dto.UpdateCategoryByIdOutputDto); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UpdateCategoryByIdOutputDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateCategoryByIdInputDto) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCategoryHandler creates a new instance of MockCategoryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryHandler {
	mock := &MockCategoryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
