// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	database "lorem-backend/internal/database"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	uuid "github.com/google/uuid"
)

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

// CreateFileMeta provides a mock function with given fields: ctx, fileMeta
func (_m *MockFileRepository) CreateFileMeta(ctx context.Context, fileMeta *database.File) (uuid.UUID, error) {
	ret := _m.Called(ctx, fileMeta)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileMeta")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.File) (uuid.UUID, error)); ok {
		return rf(ctx, fileMeta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.File) uuid.UUID); ok {
		r0 = rf(ctx, fileMeta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.File) error); ok {
		r1 = rf(ctx, fileMeta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeneratePresignUrl provides a mock function with given fields: ctx, objKey
func (_m *MockFileRepository) GeneratePresignUrl(ctx context.Context, objKey string) (string, error) {
	ret := _m.Called(ctx, objKey)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, objKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, objKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllFilesMetadata provides a mock function with given fields: ctx, page, pageSize
func (_m *MockFileRepository) GetAllFilesMetadata(ctx context.Context, page int64, pageSize int64) ([]database.File, int64, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFilesMetadata")
	}

	var r0 []database.File
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]database.File, int64, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []database.File); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) int64); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetFileMetaByID provides a mock function with given fields: ctx, fileID
func (_m *MockFileRepository) GetFileMetaByID(ctx context.Context, fileID uuid.UUID) (*database.File, error) {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMetaByID")
	}

	var r0 *database.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*database.File, error)); ok {
		return rf(ctx, fileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *database.File); ok {
		r0 = rf(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: ctx, objKey, file, size, contentType
func (_m *MockFileRepository) UploadFile(ctx context.Context, objKey string, file multipart.File, size int64, contentType string) (string, error) {
	ret := _m.Called(ctx, objKey, file, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File, int64, string) (string, error)); ok {
		return rf(ctx, objKey, file, size, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File, int64, string) string); ok {
		r0 = rf(ctx, objKey, file, size, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, multipart.File, int64, string) error); ok {
		r1 = rf(ctx, objKey, file, size, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
