// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

// GeneratePresignUrl provides a mock function with given fields: ctx, objKey
func (_m *MockObjectStorage) GeneratePresignUrl(ctx context.Context, objKey string) (string, error) {
	ret := _m.Called(ctx, objKey)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, objKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, objKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: ctx, objKey, file, size, contentType
func (_m *MockObjectStorage) UploadFile(ctx context.Context, objKey string, file multipart.File, size int64, contentType string) (string, error) {
	ret := _m.Called(ctx, objKey, file, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File, int64, string) (string, error)); ok {
		return rf(ctx, objKey, file, size, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File, int64, string) string); ok {
		r0 = rf(ctx, objKey, file, size, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, multipart.File, int64, string) error); ok {
		r1 = rf(ctx, objKey, file, size, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
